import { createClient } from '@supabase/supabase-js';

// ==========================================
// === SUPABASE CONFIGURATION ===
// ==========================================
const supabaseUrl = 'https://ouijqobcjwmclrdmtfxf.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91aWpxb2JjandtY2xyZG10ZnhmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2Nzc5OTA0MSwiZXhwIjoyMDgzMzc1MDQxfQ.PDa6vUYNtdUCdXD0a5ycKC6WfuqiYGfK4LcDSghvszw';
const supabase = createClient(supabaseUrl, supabaseKey);

export default async function handler(req, res) {
    // Only allow POST requests
    if (req.method !== 'POST') {
        return res.status(405).json({ 
            success: false, 
            error: 'Method Not Allowed' 
        });
    }

    try {
        console.log('=== Payment Request Started ===');
        console.log('Request Body:', JSON.stringify(req.body, null, 2));

        // Get data from the frontend request
        const { name, email, phone, amount, billDescription } = req.body;

        // Validate required fields
        if (!name || !email || !phone || !amount) {
            return res.status(400).json({ 
                success: false, 
                error: 'Missing required fields: name, email, phone, amount' 
            });
        }

        // === 1. SAVE ORDER TO SUPABASE ===
        let dbOrderId = null;
        
        try {
            const { data: orderData, error: dbError } = await supabase
                .from('orders')
                .insert([
                    { 
                        name: name, 
                        email: email, 
                        phone: phone, 
                        amount: parseFloat(amount),
                        status: 'pending' 
                    }
                ])
                .select();

            if (dbError) throw dbError;
            
            // Get the ID generated by Supabase
            dbOrderId = orderData[0].id;
            console.log('Order saved to Supabase. ID:', dbOrderId);

        } catch (error) {
            console.error('CRITICAL: Supabase Error:', error);
            return res.status(500).json({ 
                success: false, 
                error: 'Could not save order. Please try again.',
                details: error.message
            });
        }

        // === 2. TOYYIBPAY CONFIGURATION ===
        const categoryCode = '2mk6qgyo'; 
        const userSecretKey = 'b2kcp05o-b5m0-q000-55i7-w3j57riufv7h';
        const billName = 'ARANIS ECOM';
        const billPriceSetting = '1';
        const billPayorInfo = '1';
        
        // Convert amount to cents (RM 10.00 = 1000)
        const billAmount = `${parseFloat(amount) * 100}`; 
        
        const billReturnUrl = 'https://aranis-aiadsanalyst.vercel.app/payment-successful.html';
        const billCallbackUrl = 'https://aranis-aiadsanalyst.vercel.app/api/payment-callback';
        
        const billExternalReferenceNo = dbOrderId.toString();
        
        const billTo = name;
        const billEmail = email;
        const billPhone = phone;
        const billSplitPayment = '0';
        const billPaymentChannel = '0';
        const billChargeToCustomer = '1';

        // === FIX: Use URLSearchParams instead of FormData ===
        const params = new URLSearchParams();
        params.append('userSecretKey', userSecretKey);
        params.append('categoryCode', categoryCode);
        params.append('billName', billName);
        params.append('billDescription', billDescription || `Pembelian ARANIS - RM${amount}`);
        params.append('billPriceSetting', billPriceSetting);
        params.append('billPayorInfo', billPayorInfo);
        params.append('billAmount', billAmount);
        params.append('billReturnUrl', billReturnUrl);
        params.append('billCallbackUrl', billCallbackUrl);
        params.append('billExternalReferenceNo', billExternalReferenceNo);
        params.append('billTo', billTo);
        params.append('billEmail', billEmail);
        params.append('billPhone', billPhone);
        params.append('billSplitPayment', billSplitPayment);
        params.append('billSplitPaymentArgs', '');
        params.append('billPaymentChannel', billPaymentChannel);
        params.append('billChargeToCustomer', billChargeToCustomer);
        params.append('billExpiryDays', '1');
        params.append('billContentEmail', 'Terima kasih atas pembayaran anda. Prompt AI anda sedia untuk dimuat turun. Sila semel e-mel anda.');

        console.log('Data being sent to ToyyibPay...');

        // Make the API call to ToyyibPay from the server
        const response = await fetch('https://toyyibpay.com/index.php/api/createBill', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
            },
            body: params,
        });

        const textResult = await response.text();
        console.log('ToyyibPay Raw Response:', textResult);

        let result;
        try {
            result = JSON.parse(textResult);
            console.log('Parsed ToyyibPay Response:', JSON.stringify(result, null, 2));
        } catch (e) {
            console.error("Failed to parse ToyyibPay response:", e);
            
            // Check for maintenance message
            if (textResult.includes('FPX') && (textResult.includes('maintenance') || textResult.includes('maintainance'))) {
                return res.status(503).json({ 
                    success: false, 
                    error: 'FPX_MAINTENANCE',
                    message: 'Online Transfer FPX Sedang maintainance. Sila cuba sebentar tadi.'
                });
            }
            
            return res.status(500).json({ 
                success: false, 
                error: 'Invalid response from payment provider.',
                details: textResult
            });
        }

        // Check if the bill was created successfully
        if (result && result.length > 0 && result[0].BillCode) {
            const billCode = result[0].BillCode;
            const billUrl = `https://toyyibpay.com/${billCode}`;

            console.log('Bill created successfully! Bill Code:', billCode);

            // === FACEBOOK CODE REMOVED ===
            
            // Send the successful response back to the frontend
            return res.status(200).json({ 
                success: true, 
                billCode: billCode,
                billUrl: billUrl,
                billExternalReferenceNo: billExternalReferenceNo,
                orderId: dbOrderId 
            });
        } else {
            console.error("ToyyibPay API Error:", result);
            
            if (result && typeof result === 'object' && 
                (JSON.stringify(result).toLowerCase().includes('fpx') && 
                (JSON.stringify(result).toLowerCase().includes('maintenance') || 
                 JSON.stringify(result).toLowerCase().includes('maintainance')))) {
                return res.status(503).json({ 
                    success: false, 
                    error: 'FPX_MAINTENANCE',
                    message: 'Online Transfer FPX Sedang maintainance, Sila gunakan QR untuk Pembayaran. Terima kasih'
                });
            }
            
            return res.status(400).json({ 
                success: false, 
                error: 'Failed to create payment bill.',
                details: result
            });
        }
    } catch (error) {
        // Outer catch block to prevent HTML errors
        console.error('Server Error (Outer Catch):', error);
        return res.status(500).json({ 
            success: false, 
            error: 'An internal server error occurred.',
            details: error.message
        });
    }
}
